version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: Europe/Stockholm
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@eslint/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: Europe/Stockholm
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
